
let products = [
  {
    id: 100,
    subject: "Trigonometry",
    location: "Chelsea",
    price: 100,
    availability: 5,
    category: "Mathematics",
    imagePath: "",
  },
  {
    id: 101,
    subject: "Lexis and Structure",
    location: "Stratford",
    price: 120,
    availability: 5,
    category: "English Language",
    imagePath: "",
  },
  {
    id: 102,
    subject: "Gas Laws",
    location: "Camden Town",
    price: 90,
    availability: 5,
    category: "Chemistry",
    imagePath: "",
  },
  {
    id: 103,
    subject: "Simple Harmonic Motion",
    location: "Greenwich",
    price: 85,
    availability: 5,
    category: "Physics",
    imagePath: "",
  },
  {
    id: 104,
    subject: "Organization of Life",
    location: "Bromley",
    price: 95,
    availability: 5,
    category: "Biology",
    imagePath: "",
  },
  {
    id: 105,
    subject: "Introduction to Programming with C",
    location: "Hampstead",
    price: 150,
    availability: 5,
    category: "Computer Programming",
    imagePath: "",
  },
  {
    id: 106,
    subject: "Geometry",
    location: "Camden Town",
    price: 85,
    availability: 5,
    category: "Mathematics",
    imagePath: "",
  },
  {
    id: 107,
    subject: "Thermodynamics",
    location: "Westminster",
    price: 98,
    availability: 5,
    category: "Physics",
    imagePath: "",
  },
  {
    id: 108,
    subject: "Periodic Table of Elements",
    location: "Hendon",
    price: 90,
    availability: 5,
    category: "Chemistry",
    imagePath: "",
  },
  {
    id: 109,
    subject: "Essay Writing Made Easy",
    location: "Bromley",
    price: 100,
    availability: 5,
    category: "English Language",
    imagePath: "",
  },
  {
    id: 110,
    subject: "Theories of Evolution",
    location: "Westminster",
    price: 92,
    availability: 5,
    category: "Biology",
    imagePath: "",
  },
];
