// new vue({
//   el: "app",
//   data: {
//     sitename: "Tutor's Corner After School Class Lessons",
//     product: {
//         id: 100,
//         Subject: "Math",
//         Location: "Manchester",
//         Price: 30,
//         imagePath:
//     }
//   },
// });

let products = [
  {
    id: 100,
    subject: "Trigonometry",
    location: "Chelsea",
    price: "100",
    availability: 5,
    category: "Mathematics",
    imagePath: "",
  },
  {
    id: 101,
    subject: "Lexis and Structure",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "English Language",
    imagePath: "",
  },
  {
    id: 102,
    subject: "Gas Laws",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Chemistry",
    imagePath: "",
  },
  {
    id: 103,
    subject: "Simple Harmonic Motion",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Physics",
    imagePath: "",
  },
  {
    id: 104,
    subject: "Organization of Life",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Biology",
    imagePath: "",
  },
  {
    id: 105,
    subject: "Introduction to Programming with C",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Computer Programming",
    imagePath: "",
  },
  {
    id: 106,
    subject: "Geometry",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Mathematics",
    imagePath: "",
  },
  {
    id: 107,
    subject: "Thermodynamics",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Physics",
    imagePath: "",
  },
  {
    id: 108,
    subject: "Periodic Table of Elements",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Chemistry",
    imagePath: "",
  },
  {
    id: 109,
    subject: "Essay Writing Made Easy",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "English Language",
    imagePath: "",
  },
  {
    id: 110,
    subject: "Theories of Evolution",
    location: "Camden Town",
    price: "100",
    availability: 5,
    category: "Biology",
    imagePath: "",
  },
];
